config/routes.rb
Rails.application.routes.draw do
    devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'post#index'
    #resources :post do
    #  get :new
    #end
    get 'posts', to: 'post#index'
    get 'posts/new', to: 'post#new'
    post 'posts', to: 'post#create'
    get 'posts/:id', to: 'post#show'
    get 'posts/:id/edit', to: 'post#edit', as: :edit_post
    patch 'posts/:id/edit', to: 'post#update'
    delete 'posts/:id/delete', to: 'post#destroy', as: :delete_post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/post_controller.rb
class PostController < ApplicationController
    before_action :configure_permitted_parameters, :authenticate_user!, if: :devise_controller?

    def index
        if(user_signed_in?)
            @post_data = Post.all.order("created_at DESC");
        else
            #render :new_user_session
        end
        #p @post_data
    end

    def new
        #@post = Post.new
        #@post = (Post.new) 
    end

    def create
        if(user_signed_in?)
            @post_data = Post.new(post_params)
            if @post_data.save
                redirect_to posts_path
                #redirect_to post_index_path
            else
                render :new
            end
        else
            render :new_user_session
        end
    end

    def show
        @post_single_data = Post.find(params[:id]);
    end

    def edit
        # p params[:id]
        @post_edit_data = Post.find(params[:id]);

        Rails.logger.debug("My object: #{@post_edit_data.inspect}");
    end

    def update
        @post_update_data = Post.find(params[:id]);

        if @post_update_data.update(post_params)
            redirect_to posts_path
            #redirect_to post_index_path
        else
            render :new
        end
    end

    def destroy
        @post_delete_data = Post.find(params[:id]);
        @post_delete_data.destroy

        redirect_to posts_path
        #redirect_to post_index_path
    end

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password])
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_in) do |user_params|
            user_params.permit(:username, :email)
        end
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) do |user_params|
            user_params.permit({ roles: [] }, :email, :password, :password_confirmation)
        end
    end

    private
    def post_params
        params.required(:post).permit(:title, :body)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorial</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post/edit.html.erb
<div class="container">
    <h5>Edit Post</h5>

    <%= simple_form_for @post_edit_data, url: edit_post_path do |f| %>

    <%= f.input :title %> <br>

    <%= f.input :body %> <br>

    <%= f.submit :class=>'btn btn-primary' %>

    <% end %>
</div>

app/views/post/form.html.erb
<%= simple_form_for(@post) do |f| %>

<%= f.input :title,  %> <br>

<%= f.input :body %> <br>

<%= f.submit %>

<% end %>

app/views/post/index.html.erb
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
</style>

<%= link_to "New Post", posts_new_path %>
<%= link_to "Logout", destroy_user_session_path, :method => :delete  %>
<br><br>

<table style="width:100%">
    <tr>
        <th>Title</th>
        <th>Body</th>
        <th>Created At</th>
        <th>Actions</th>
    </tr>
    <% if @post_data.present? %>
    <% @post_data.each do |posts| %>
        <tr>
            <td>
                <%= posts.title %>
            </td>

            <td>
                <%= posts.body %>
            </td>

            <td>
                <%= posts.created_at %>
            </td>

            <td>
                <%= link_to "show", posts_path(id: posts.id) %> <br>
                <%= link_to "edit", edit_post_path(id: posts.id) %> <br>
                <%= link_to "delete", delete_post_path(posts), method: :delete %>
            </td>
        </tr>
    <% end %>
    <% else %>
    <% end %>
</table>

app/views/post/new.html.erb
<h1> New Post </h1>

<%= simple_form_for Post.new do |f| %>

<%= f.input :title %> <br>

<%= f.input :body %> <br>

<%= f.submit %>

<% end %>

app/views/post/show.html.erb
<label>Title:</label> <%= @post_single_data.title %> <br>
<label>Body:</label> <%= @post_single_data.body %> <br><br><br>

<%= link_to "All Posts", posts_path %>